### ISSUE TITLE
Punk Idea: Add homepage opengraph data: image, description, etc..

### ISSUE THREAD

**Issue by mkubdev** [StreetCommunityProgrammer/metaphore#33]
### Is your mind blowing punk idea is something that ~~wrong~~ different then other.

Kubdev#6277

### Tell me what you want to suggest

Update the homepage to add opengraph metatag like `image`, `description`, `title` ..

**Comment by darkterminal** [comment]
Sure! I need to configure them. But before going on there. I need to fix our metaphor Github Action to generate new story.
