### ISSUE TITLE
FIX: add responsiveness 

### ISSUE THREAD

**Issue by mkubdev** [StreetCommunityProgrammer/metaphore#35]
### Is your mind blowing punk idea is something that ~~wrong~~ different then other.

mod@scp.com

### Tell me what you want to suggest

We need to implement the responsive class of tailwind.
I’ll self assign this task.

**Comment by darkterminal** [comment]
That's good, some feedback talking about responsiveness... :smile: :fire:

**Comment by darkterminal** [comment]
Every detail need work an art!
