### ISSUE TITLE
Request to Fix Inline `code` line Inside The Story Content

### ISSUE THREAD

**Issue by mkubdev** [StreetCommunityProgrammer/metaphore#53]
### Is your mind blowing punk idea is something that ~~wrong~~ different then other.

mod@scp.com

### Tell me what you want to suggest

Inline `code` text doesn't render from issue to story.
related to #48

**Comment by darkterminal** [comment]
Is this what you mean?
![image](https://user-images.githubusercontent.com/32319439/229483943-37cc1137-ccbc-45b1-b799-59e46a8facbf.png)

**Comment by mkubdev** [comment]
> @mkubdev Is this what you mean? ![image](https://user-images.githubusercontent.com/32319439/229483943-37cc1137-ccbc-45b1-b799-59e46a8facbf.png)

Exactly!

**Comment by darkterminal** [comment]
`@heroicons/react/24/solid` and `icon` is using single quote (`'`) not back-tick (`). So it's not parse

**Comment by mkubdev** [comment]
> `@heroicons/react/24/solid` and `icon` is using single quote (`'`) not back-tick (`). So it's not converted as inline code.

Oh, well spotted

**Comment by darkterminal** [comment]
Already solve!
