### ISSUE TITLE
Punk Idea: Add C/C++ stories

### ISSUE THREAD

**Issue by Panquesito7** [StreetCommunityProgrammer/metaphore#71]
### Is your mind blowing punk idea is something that ~~wrong~~ different then other.

Panquesito7#3723

### Tell me what you want to suggest

It'd be great if we could add C/C++ stories to the list of stories.
I have a few (and plan to make more in the future) that I'd like to add. 🙂

**Comment by darkterminal** [comment]
You can make it by make PR about that... then do it! 🔥

**Comment by darkterminal** [comment]
Yup! We need create one for that
