### ISSUE TITLE
[OTHER]: There should be a space between 'Next.Js' Image and 'host' in  footer.jsx

### ISSUE THREAD

**Issue by SaketKaswa20** [StreetCommunityProgrammer/metaphore#77]
### What would you like to share?

In the footer, in the bottom right corner there should be space between the 'Next.Js' Image and the word 'host' .

### Additional information

<img width="257" alt="Screenshot 2023-07-23 at 6 09 19 PM" src="https://github.com/StreetCommunityProgrammer/metaphore/assets/105808363/1dd8979a-57fd-4f63-9bd2-8193553d78e0">

**Comment by darkterminal** [comment]
Hi @SaketKaswa20 thank you for your feedback, it's been fixed.
